### ISSUE TITLE
Character avatars with transparency become opaque.

### ISSUE THREAD

**Issue by thatguyinoz** [LenAnderson/SillyTavern-LandingPage#1]
Hi, thanks for your great work.
I have created  some character avatars with transparent layer, saved as png files to replicate your example `/README/center.jpg.` loading these avatar images initially worked as expected and the landing page showed the character image with the background visible through the transparent portion.
After  a couple of chat sessions,the image seems to have changed, with the transparent portion becoming black.
Reloading the original png with transparent layer, made no difference. All avatar images present with black instead of transparent.
What further debug can i do to help find the cause of this?

thanks

**Comment by LenAnderson** [comment]
Are you using avatars or expression images on landing page? SillyTavern by default saves avatars as jpg, which replaces transparency with black. If you want to have avatars with transparency you'll have to change your SillyTavern config.

Right click the image in question on the landing page and open / save the image. Check whether the black is part of the image.

Depending on the display style you select for landing page you may get a background color behind the cards. What this color is and whether it is transparent or not depends on your SillyTavern theme.

**Comment by thatguyinoz** [comment]
Thanks for explaining that. I dont use the expressions addon, so I just created a <CharName> folder in /public/character/ and put the required png in that folder and  named it neutral.png. then selected neutral in the landing page settings. :-) Now if only I could do that for a specific group pic.
